version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ./src
jobs:
  build:
    executor: my-executor

    steps: #stepsキーが正しい
      - checkout
      - run: pwd
      - run: python HelloWorld.py
